language: python
python:
  - "2.7"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - pytest --cov=app --cov-report=term-missing
  
after_success:
  - coveralls