
language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - coverage run --source=app -m pytest && coverage report
after_success:
    - coveralls